//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./fireworks_types');
//HELPER FUNCTIONS AND STRUCTURES

AgentVsAgent.Fireworks_enter_arena_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    }
  }
};
AgentVsAgent.Fireworks_enter_arena_args.prototype = {};
AgentVsAgent.Fireworks_enter_arena_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.EntryRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentVsAgent.Fireworks_enter_arena_args.prototype.write = function(output) {
  output.writeStructBegin('Fireworks_enter_arena_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentVsAgent.Fireworks_enter_arena_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
AgentVsAgent.Fireworks_enter_arena_result.prototype = {};
AgentVsAgent.Fireworks_enter_arena_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.EntryResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentVsAgent.Fireworks_enter_arena_result.prototype.write = function(output) {
  output.writeStructBegin('Fireworks_enter_arena_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentVsAgent.Fireworks_get_game_info_args = function(args) {
  this.ticket = null;
  if (args) {
    if (args.ticket !== undefined) {
      this.ticket = args.ticket;
    }
  }
};
AgentVsAgent.Fireworks_get_game_info_args.prototype = {};
AgentVsAgent.Fireworks_get_game_info_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ticket = new ttypes.Ticket();
        this.ticket.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentVsAgent.Fireworks_get_game_info_args.prototype.write = function(output) {
  output.writeStructBegin('Fireworks_get_game_info_args');
  if (this.ticket !== null && this.ticket !== undefined) {
    output.writeFieldBegin('ticket', Thrift.Type.STRUCT, 1);
    this.ticket.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentVsAgent.Fireworks_get_game_info_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.GameException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ex !== undefined) {
      this.ex = args.ex;
    }
  }
};
AgentVsAgent.Fireworks_get_game_info_result.prototype = {};
AgentVsAgent.Fireworks_get_game_info_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.GameInfo();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.GameException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentVsAgent.Fireworks_get_game_info_result.prototype.write = function(output) {
  output.writeStructBegin('Fireworks_get_game_info_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentVsAgent.Fireworks_get_game_result_args = function(args) {
  this.ticket = null;
  if (args) {
    if (args.ticket !== undefined) {
      this.ticket = args.ticket;
    }
  }
};
AgentVsAgent.Fireworks_get_game_result_args.prototype = {};
AgentVsAgent.Fireworks_get_game_result_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ticket = new ttypes.Ticket();
        this.ticket.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentVsAgent.Fireworks_get_game_result_args.prototype.write = function(output) {
  output.writeStructBegin('Fireworks_get_game_result_args');
  if (this.ticket !== null && this.ticket !== undefined) {
    output.writeFieldBegin('ticket', Thrift.Type.STRUCT, 1);
    this.ticket.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentVsAgent.Fireworks_get_game_result_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.GameException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ex !== undefined) {
      this.ex = args.ex;
    }
  }
};
AgentVsAgent.Fireworks_get_game_result_result.prototype = {};
AgentVsAgent.Fireworks_get_game_result_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.GameResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.GameException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AgentVsAgent.Fireworks_get_game_result_result.prototype.write = function(output) {
  output.writeStructBegin('Fireworks_get_game_result_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AgentVsAgent.FireworksClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
AgentVsAgent.FireworksClient.prototype = {};
AgentVsAgent.FireworksClient.prototype.enter_arena = function(request, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_enter_arena(request);
};

AgentVsAgent.FireworksClient.prototype.send_enter_arena = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('enter_arena', Thrift.MessageType.CALL, this.seqid);
  var args = new AgentVsAgent.Fireworks_enter_arena_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentVsAgent.FireworksClient.prototype.recv_enter_arena = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentVsAgent.Fireworks_enter_arena_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('enter_arena failed: unknown result');
};
AgentVsAgent.FireworksClient.prototype.get_game_info = function(ticket, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_get_game_info(ticket);
};

AgentVsAgent.FireworksClient.prototype.send_get_game_info = function(ticket) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_game_info', Thrift.MessageType.CALL, this.seqid);
  var args = new AgentVsAgent.Fireworks_get_game_info_args();
  args.ticket = ticket;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentVsAgent.FireworksClient.prototype.recv_get_game_info = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentVsAgent.Fireworks_get_game_info_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_game_info failed: unknown result');
};
AgentVsAgent.FireworksClient.prototype.get_game_result = function(ticket, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_get_game_result(ticket);
};

AgentVsAgent.FireworksClient.prototype.send_get_game_result = function(ticket) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_game_result', Thrift.MessageType.CALL, this.seqid);
  var args = new AgentVsAgent.Fireworks_get_game_result_args();
  args.ticket = ticket;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AgentVsAgent.FireworksClient.prototype.recv_get_game_result = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AgentVsAgent.Fireworks_get_game_result_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_game_result failed: unknown result');
};
AgentVsAgent.FireworksProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
AgentVsAgent.FireworksProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

AgentVsAgent.FireworksProcessor.prototype.process_enter_arena = function(seqid, input, output) {
  var args = new AgentVsAgent.Fireworks_enter_arena_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.enter_arena(args.request, function (err, result) {
    var result = new AgentVsAgent.Fireworks_enter_arena_result((err != null ? err : {success: result}));
    output.writeMessageBegin("enter_arena", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

AgentVsAgent.FireworksProcessor.prototype.process_get_game_info = function(seqid, input, output) {
  var args = new AgentVsAgent.Fireworks_get_game_info_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.get_game_info(args.ticket, function (err, result) {
    var result = new AgentVsAgent.Fireworks_get_game_info_result((err != null ? err : {success: result}));
    output.writeMessageBegin("get_game_info", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

AgentVsAgent.FireworksProcessor.prototype.process_get_game_result = function(seqid, input, output) {
  var args = new AgentVsAgent.Fireworks_get_game_result_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.get_game_result(args.ticket, function (err, result) {
    var result = new AgentVsAgent.Fireworks_get_game_result_result((err != null ? err : {success: result}));
    output.writeMessageBegin("get_game_result", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

