//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./hearts_types');
//HELPER FUNCTIONS AND STRUCTURES

Hearts_get_game_args = function(args) {
};
Hearts_get_game_args.prototype = {};
Hearts_get_game_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Hearts_get_game_args.prototype.write = function(output) {
  output.writeStructBegin('Hearts_get_game_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Hearts_get_game_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
Hearts_get_game_result.prototype = {};
Hearts_get_game_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Hearts_get_game_result.prototype.write = function(output) {
  output.writeStructBegin('Hearts_get_game_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Hearts_play_card_args = function(args) {
  this.card = null;
  if (args) {
    if (args.card !== undefined) {
      this.card = args.card;
    }
  }
};
Hearts_play_card_args.prototype = {};
Hearts_play_card_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.card = new ttypes.Card();
        this.card.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Hearts_play_card_args.prototype.write = function(output) {
  output.writeStructBegin('Hearts_play_card_args');
  if (this.card !== null && this.card !== undefined) {
    output.writeFieldBegin('card', Thrift.Type.STRUCT, 1);
    this.card.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Hearts_play_card_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
Hearts_play_card_result.prototype = {};
Hearts_play_card_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Hearts_play_card_result.prototype.write = function(output) {
  output.writeStructBegin('Hearts_play_card_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HeartsClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
HeartsClient.prototype = {};
HeartsClient.prototype.get_game = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_get_game();
};

HeartsClient.prototype.send_get_game = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_game', Thrift.MessageType.CALL, this.seqid);
  var args = new Hearts_get_game_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HeartsClient.prototype.recv_get_game = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Hearts_get_game_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_game failed: unknown result');
};
HeartsClient.prototype.play_card = function(card, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_play_card(card);
};

HeartsClient.prototype.send_play_card = function(card) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('play_card', Thrift.MessageType.CALL, this.seqid);
  var args = new Hearts_play_card_args();
  args.card = card;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HeartsClient.prototype.recv_play_card = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Hearts_play_card_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('play_card failed: unknown result');
};
HeartsProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
HeartsProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

HeartsProcessor.prototype.process_get_game = function(seqid, input, output) {
  var args = new Hearts_get_game_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.get_game(function (err, result) {
    var result = new Hearts_get_game_result((err != null ? err : {success: result}));
    output.writeMessageBegin("get_game", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

HeartsProcessor.prototype.process_play_card = function(seqid, input, output) {
  var args = new Hearts_play_card_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.play_card(args.card, function (err, result) {
    var result = new Hearts_play_card_result((err != null ? err : {success: result}));
    output.writeMessageBegin("play_card", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

