all: MyBot

clean:
	@echo 'Nothing to clean'

MyBot:
	@echo 'Nothing to compile'

run:
	java -jar ../common/tools/PlayGame.jar ../common/maps/map1.txt 1000 200 log.txt "ruby MyBot.rb" "java -jar ../common/examples/DualBot.jar" | java -jar ../common/tools/ShowGame.jar
