//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var ttypes = module.exports = {};
ttypes.Suit = {
'CLUBS' : 21,
'DIAMONDS' : 22,
'SPADES' : 23,
'HEARTS' : 24
};
ttypes.Rank = {
'ACE' : 1,
'TWO' : 2,
'THREE' : 3,
'FOUR' : 4,
'FIVE' : 5,
'SIX' : 6,
'SEVEN' : 7,
'EIGHT' : 8,
'NINE' : 9,
'TEN' : 10,
'JACK' : 11,
'QUEEN' : 12,
'KING' : 13
};
ttypes.Position = {
'NORTH' : 1,
'EAST' : 2,
'SOUTH' : 3,
'WEST' : 4
};
Card = module.exports.Card = function(args) {
  this.suit = null;
  this.rank = null;
  if (args) {
    if (args.suit !== undefined) {
      this.suit = args.suit;
    }
    if (args.rank !== undefined) {
      this.rank = args.rank;
    }
  }
};
Card.prototype = {};
Card.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.suit = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.rank = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Card.prototype.write = function(output) {
  output.writeStructBegin('Card');
  if (this.suit !== null && this.suit !== undefined) {
    output.writeFieldBegin('suit', Thrift.Type.I32, 1);
    output.writeI32(this.suit);
    output.writeFieldEnd();
  }
  if (this.rank !== null && this.rank !== undefined) {
    output.writeFieldBegin('rank', Thrift.Type.I32, 2);
    output.writeI32(this.rank);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Ticket = module.exports.Ticket = function(args) {
  this.gameId = null;
  this.agentId = null;
  if (args) {
    if (args.gameId !== undefined) {
      this.gameId = args.gameId;
    }
    if (args.agentId !== undefined) {
      this.agentId = args.agentId;
    }
  }
};
Ticket.prototype = {};
Ticket.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.gameId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.agentId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Ticket.prototype.write = function(output) {
  output.writeStructBegin('Ticket');
  if (this.gameId !== null && this.gameId !== undefined) {
    output.writeFieldBegin('gameId', Thrift.Type.STRING, 1);
    output.writeString(this.gameId);
    output.writeFieldEnd();
  }
  if (this.agentId !== null && this.agentId !== undefined) {
    output.writeFieldBegin('agentId', Thrift.Type.STRING, 2);
    output.writeString(this.agentId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

EntryResponse = module.exports.EntryResponse = function(args) {
  this.ticket = null;
  this.message = null;
  if (args) {
    if (args.ticket !== undefined) {
      this.ticket = args.ticket;
    }
    if (args.message !== undefined) {
      this.message = args.message;
    }
  }
};
EntryResponse.prototype = {};
EntryResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ticket = new ttypes.Ticket();
        this.ticket.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.message = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EntryResponse.prototype.write = function(output) {
  output.writeStructBegin('EntryResponse');
  if (this.ticket !== null && this.ticket !== undefined) {
    output.writeFieldBegin('ticket', Thrift.Type.STRUCT, 1);
    this.ticket.write(output);
    output.writeFieldEnd();
  }
  if (this.message !== null && this.message !== undefined) {
    output.writeFieldBegin('message', Thrift.Type.STRING, 2);
    output.writeString(this.message);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GameInfo = module.exports.GameInfo = function(args) {
  this.position = null;
  if (args) {
    if (args.position !== undefined) {
      this.position = args.position;
    }
  }
};
GameInfo.prototype = {};
GameInfo.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.position = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GameInfo.prototype.write = function(output) {
  output.writeStructBegin('GameInfo');
  if (this.position !== null && this.position !== undefined) {
    output.writeFieldBegin('position', Thrift.Type.I32, 1);
    output.writeI32(this.position);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Trick = module.exports.Trick = function(args) {
  this.leader = null;
  this.north = null;
  this.east = null;
  this.south = null;
  this.west = null;
  if (args) {
    if (args.leader !== undefined) {
      this.leader = args.leader;
    }
    if (args.north !== undefined) {
      this.north = args.north;
    }
    if (args.east !== undefined) {
      this.east = args.east;
    }
    if (args.south !== undefined) {
      this.south = args.south;
    }
    if (args.west !== undefined) {
      this.west = args.west;
    }
  }
};
Trick.prototype = {};
Trick.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.leader = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.north = new ttypes.Card();
        this.north.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.east = new ttypes.Card();
        this.east.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRUCT) {
        this.south = new ttypes.Card();
        this.south.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRUCT) {
        this.west = new ttypes.Card();
        this.west.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Trick.prototype.write = function(output) {
  output.writeStructBegin('Trick');
  if (this.leader !== null && this.leader !== undefined) {
    output.writeFieldBegin('leader', Thrift.Type.I32, 1);
    output.writeI32(this.leader);
    output.writeFieldEnd();
  }
  if (this.north !== null && this.north !== undefined) {
    output.writeFieldBegin('north', Thrift.Type.STRUCT, 2);
    this.north.write(output);
    output.writeFieldEnd();
  }
  if (this.east !== null && this.east !== undefined) {
    output.writeFieldBegin('east', Thrift.Type.STRUCT, 3);
    this.east.write(output);
    output.writeFieldEnd();
  }
  if (this.south !== null && this.south !== undefined) {
    output.writeFieldBegin('south', Thrift.Type.STRUCT, 4);
    this.south.write(output);
    output.writeFieldEnd();
  }
  if (this.west !== null && this.west !== undefined) {
    output.writeFieldBegin('west', Thrift.Type.STRUCT, 5);
    this.west.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

